FROM python:3.8-alpine as base

FROM base as builder

RUN mkdir /install
WORKDIR /install

COPY requirements.txt /requirements.txt

RUN pip3 install --prefix=/install --no-warn-script-location -r /requirements.txt

FROM base

COPY --from=builder /install /usr/local

WORKDIR /var/lib/micado/submitter

COPY submitter .

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8 PYTHONPATH=/var/lib/micado

ENTRYPOINT ["gunicorn", "submitter.api:app", "--timeout", "600", "--workers", "1"]