main_config:
  dry_run: True
logging:
  version: 1
  disable_existing_loggers: True
  root:
    handlers: [console, file]
    level: DEBUG
  formatters:
    simpleFormatter:
      format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  loggers:
    submitter:
      handlers: [console, file]
      propagate: False
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simpleFormatter
      level: INFO
      stream: ext://sys.stdout
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: simpleFormatter
      level: DEBUG
      mode: a
      filename: /var/log/submitter/submitter.log
      maxBytes: 52428800
      backupCount: 3

step:
  translate:
    - SecurityPolicyManagerAdaptor
    - KubernetesAdaptor
    - TerraformAdaptor
    - PkAdaptor
  execute:
    - SecurityPolicyManagerAdaptor
    - TerraformAdaptor
    - KubernetesAdaptor
    - PkAdaptor
  update:
    - SecurityPolicyManagerAdaptor
    - TerraformAdaptor
    - KubernetesAdaptor
    - PkAdaptor
  undeploy:
    - PkAdaptor
    - KubernetesAdaptor
    - TerraformAdaptor
    - SecurityPolicyManagerAdaptor
  cleanup:
    - KubernetesAdaptor
    - TerraformAdaptor
    - PkAdaptor
    - SecurityPolicyManagerAdaptor

adaptor_config:
  KubernetesAdaptor:
    types:
      - "tosca.nodes.MiCADO.Container.Application.Docker"
      - "tosca.policies.Security.MiCADO.Network.*"
    endoint: "endpoint"
    volume: "./files/output_configs/"
    unvalidated_kinds:
    - ClusterIssuer
    - Certificate
    k8s_version: 1.18.0

  TerraformAdaptor:
    types:
      - "tosca.nodes.MiCADO.Terraform.*"
    endoint: "endpoint"
    volume: "./files/output_configs/"

  PkAdaptor:
    types:
      - "tosca.policies.Scaling.MiCADO"
    endpoint: "policykeeper:12345"
    volume: "./files/output_configs/"

  SecurityPolicyManagerAdaptor:
    types:
      - "tosca.policies.Security.MiCADO.Secret.KubernetesSecretDistribution"
    endoint: "endpoint"
    volume: "./files/output_configs/"
