---
- name: Join k3s cluster
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -s - 
    --server "https://{{ hostvars['micado']['ansible_host'] }}:6443"
    --node-name "{{ inventory_hostname | lower }}"
    --token "{{ hostvars['micado']['k3s_token']['content'] | b64decode | trim }}"
    --node-external-ip "{{ ansible_host }}"

- name: (registries) Checking the existence of registry credentials
  stat: path={{ registry_cred_path }}
  become: false
  delegate_to: localhost
  register: reg_creds

- name: (registries) Ensure /etc/rancher/k3s directory
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
  when: reg_creds.stat.exists

- name: (registries) Copy registries.yaml
  copy:
    src: "{{ registry_cred_path }}"
    dest: /etc/rancher/k3s/registries.yaml
  when: reg_creds.stat.exists
