---
- name: Join k3s cluster
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -s - 
    --server "https://{{ hostvars['micado']['ansible_host'] }}:6443"
    --node-name "{{ inventory_hostname | lower }}"
    --token "{{ hostvars['micado']['k3s_token']['content'] | b64decode | trim }}"
    --node-external-ip "{{ ansible_host }}"

- name: (registries) Ensure /etc/rancher/k3s directory
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
  when: registries_file.stat.exists

- name: (registries) Copy registries.yaml
  copy:
    content: "{{ registries_content['content'] | b64decode }}"
    dest: /etc/rancher/k3s/registries.yaml
  when: registries_file.stat.exists
